workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      java: 17
    scripts:
      - name: Build Android APK
        script: |
          cd Albasit_Plus_Native_AndroidIDE
          gradle assembleDebug --warning-mode none --no-daemon
    artifacts:
      - Albasit_Plus_Native_AndroidIDE/app/build/outputs/**/*.apk
