workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 30
    instance_type: mac_mini_m1
    working_directory: Albasit_Plus_Native_AndroidIDE
    scripts:
      - name: Build Android APK
        script: |
          chmod +x gradlew
          ./gradlew assembleDebug
    artifacts:
      - Albasit_Plus_Native_AndroidIDE/app/build/outputs/**/*.apk
